### ISSUE TITLE
Provide OBO export

### ISSUE THREAD

**Issue by cthoyt** [OpenLHS/CVDO#1]
This is listed in OBO foundry, but without an OBO file. Can you please apply one of the standard owl2obo converters and add it? Thanks!

**Comment by pfabry** [comment]
Hello, a new version including an obo file is now available.
Considering the obo format, please note that:
 - it is not required by the OBO foundry: http://www.obofoundry.org/principles/fp-002-format.html
 - it has several limitations compared to OWL2. For instance we can only have one label or definition per class, which requires additional filtering work as we develop bilingual ontologies.

**Comment by ethierjf** [comment]
Ben dans ce cas, pourquoi on inclut le fichier obo si ce n'est pas nécessaire et si c'est incomplet (car pas bilingue)? Sinon, comme je disais, je mettrais les étiquettes et définitions française. Il faut en reparler avec Adrien.

Merci 😀👍

Jean-François Ethier, Université de Sherbrooke, GRIIS.CA
________________________________

**Comment by pfabry** [comment]
En fait, la version de CVDO sur notre GitHub est unilangue anglais. Comme j'ai remis à jour l'ontologie j'en ai profité pour faire une version obo.

________________________________
De : ethierjf <notifications@github.com>
Envoyé : 5 mars 2020 19:45
À : OpenLHS/CVDO <CVDO@noreply.github.com>
Cc : Paul Fabry <Paul.Fabry@USherbrooke.ca>; Comment <comment@noreply.github.com>
Objet : Re: [OpenLHS/CVDO] Provide OBO export (#1)

Ben dans ce cas, pourquoi on inclut le fichier obo si ce n'est pas nécessaire et si c'est incomplet (car pas bilingue)? Sinon, comme je disais, je mettrais les étiquettes et définitions française. Il faut en reparler avec Adrien.

Merci 😀👍

Jean-François Ethier, Université de Sherbrooke, GRIIS.CA
________________________________

**Comment by ethierjf** [comment]
Ah oui c'est vrai. Bon parfait alors. Maintenant, les gens auront encore moins de raison de ne pas la réutiliser ou reprendre le nom!!

Jean-François Ethier, Université de Sherbrooke, GRIIS.CA
________________________________

**Comment by pfabry** [comment]
New obo version generated with ROBOT 1.9.0

**Comment by cthoyt** [comment]
thanks!
